// Generated by scripts/generate-research-metadata.mjs. Do not edit by hand.
import { article as article0 } from "./massachusetts-solar-cost-2026";
import { article as article1 } from "./solar-sales-financing-after-complaint";
import { article as article2 } from "./sunrun-25-year-solar-contracts";
import { article as article3 } from "./sunrun-home-depot-sales-home-visit";

const discoveredArticles = [
  article0,
  article1,
  article2,
  article3,
];

export const researchArticles = new Map(
  discoveredArticles.map((article) => [article.story.slug, article]),
);

export function getResearchArticle(slug: string) {
  return researchArticles.get(slug);
}

export function getResearchContent(slug: string) {
  const article = getResearchArticle(slug);
  return article ? { Body: article.Body, ...article.config } : undefined;
}
