import type { Metadata } from "next";
import Link from "next/link";
import { InfoPage } from "../../../components/info-page";

const canonicalUrl = "https://solarcomplaint.com/research/sunrun-25-year-solar-contracts";
const sec10k = "https://www.sec.gov/Archives/edgar/data/1469367/000162828026012289/run-20251231.htm";
const q2Results = "https://www.sec.gov/Archives/edgar/data/1469367/000162828026053349/exhibit991q226.htm";
const q2TenQ = "https://www.sec.gov/Archives/edgar/data/1469367/000162828026053366/run-20260630.htm";
const secFleetReview = "https://www.sec.gov/Archives/edgar/data/1469367/000119312526167137/d147968dex991.htm";
const sunrunFaq = "https://www.sunrun.com/go-solar-center/solar-faq";
const sunrunTransfer = "https://www.sunrun.com/go-solar-center/solar-terms/definition/service-transfer";
const ftcSolar = "https://consumer.ftc.gov/articles/solar-power-your-home";

export const metadata: Metadata = {
  title: "Sunrun 25-Year Contract: Lease, PPA, Transfer & Buyout Terms",
  description: "Researching a Sunrun 25-year solar contract? See current 2026 SEC records on lease and PPA terms, performance guarantees, home-sale transfers, buyout options and how Sunrun values long-term customer agreements.",
  keywords: ["Sunrun 25 year contract", "Sunrun solar contract", "Sunrun lease 25 years", "Sunrun PPA", "Sunrun contract terms", "Sunrun solar lease", "Sunrun contract transfer", "Sunrun buyout", "Sunrun performance guarantee", "Sunrun Flex"],
  alternates: { canonical: "/research/sunrun-25-year-solar-contracts" },
  openGraph: {
    title: "Sunrun 25-Year Contracts: What Homeowners Should Know in 2026",
    description: "Current SEC records explain the term, performance guarantees, transfers and financial value behind Sunrun leases and PPAs.",
    url: "/research/sunrun-25-year-solar-contracts",
    type: "article",
    publishedTime: "2026-09-07",
    modifiedTime: "2026-09-16",
    authors: ["https://solarcomplaint.com/about"],
    section: "Research",
    images: [{ url: "https://solarcomplaint.com/og.png", width: 1200, height: 630, alt: "Sunrun 25-year solar contract research" }],
  },
  twitter: { card: "summary_large_image", title: "Sunrun 25-Year Contract: Lease, PPA, Transfer & Buyout Terms", description: "Current 2026 records on what a long-term Sunrun agreement means for homeowners.", images: ["https://solarcomplaint.com/og.png"] },
};

export default function SunrunContractsEditorial() {
  const structuredData = {
    "@context": "https://schema.org",
    "@graph": [
      { "@type": "Article", "@id": `${canonicalUrl}#article`, headline: "Sunrun 25-Year Contract: Lease, PPA, Transfer & Buyout Terms", description: "Current 2026 research on Sunrun solar leases and PPAs, including contract length, performance guarantees, transfers, end-of-term options and investor valuation.", datePublished: "2026-09-07", dateModified: "2026-09-16", inLanguage: "en-US", articleSection: "Research", mainEntityOfPage: { "@type": "WebPage", "@id": canonicalUrl }, author: { "@type": "Organization", name: "Solar Consumer Research", url: "https://solarcomplaint.com/about" }, publisher: { "@id": "https://solarcomplaint.com/#publisher" }, about: [{ "@type": "Organization", name: "Sunrun Inc." }, { "@type": "Thing", name: "Residential solar leases" }, { "@type": "Thing", name: "Solar power purchase agreements" }], citation: [sec10k, q2Results, q2TenQ, secFleetReview, sunrunFaq, sunrunTransfer, ftcSolar] },
      { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://solarcomplaint.com/" }, { "@type": "ListItem", position: 2, name: "Research", item: "https://solarcomplaint.com/research" }, { "@type": "ListItem", position: 3, name: "Sunrun 25-Year Solar Contracts", item: canonicalUrl }] }
    ]
  };

  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />
    <InfoPage className="research-story-page" eyebrow="Research · Updated September 16, 2026" title="Sunrun 25-Year Solar Contracts" lede="A Sunrun lease or power purchase agreement can last longer than many homeowners stay in the same house. New 2026 SEC records add unusually specific details about what those agreements contain and how Sunrun values them.">
      <nav className="case-question-links" aria-label="Breadcrumb"><Link href="/">Home</Link><Link href="/research">Research</Link><Link href="/companies/sunrun">Sunrun</Link><span aria-current="page">25-year contracts</span></nav>
      <nav className="case-question-links" aria-label="Article navigation"><a href="#new">New in 2026</a><a href="#term">Contract length</a><a href="#guarantee">Performance guarantee</a><a href="#transfer">Selling the home</a><a href="#end">End of term</a><a href="#investor">Investor value</a><a href="#questions">Contract checklist</a><a href="#sources">Sources</a></nav>

      <section className="info-section case-notice"><strong>The short version</strong><p>Sunrun says its Customer Agreements typically start with 20- or 25-year terms. A 2026 SEC-filed review says Sunrun’s newer SHIFT and Flex agreements typically run 25 years and that performance guarantees in reviewed agreements can vary. Sunrun’s own investor math can extend beyond the initial contract: for a 25-year agreement, it assumes a five-year renewal when calculating Subscriber Value.</p></section>

      <section id="new" className="info-section"><p className="eyebrow">Fresh records</p><h2>What new 2026 SEC filings tell us about Sunrun contracts</h2><p>An April 2026 third-party review filed with the SEC examined Sunrun’s solar fleet and sample customer agreements. It says Sunrun began offering SHIFT, Flex and Storage Add-on agreements in 2024. The reviewed SHIFT and Flex agreements typically had 25-year terms. The storage-only lease was described as having a 10-year term.</p><p>The same filing says newer agreements reviewed for the report carried performance-guarantee percentages of 90%, 85% or 0%, depending on the agreement. That is important: the words <em>performance guarantee</em> do not by themselves tell a homeowner how much production is guaranteed. The percentage and calculation in the individual agreement matter.</p><p><a href={secFleetReview} target="_blank" rel="noreferrer">Read the April 2026 fleet review filed with the SEC ↗</a></p></section>

      <section id="term" className="info-section"><h2>How long is a Sunrun solar contract?</h2><p>Sunrun’s 2025 Form 10-K and June 2026 Form 10-Q describe Customer Agreements as typically having initial terms of 20 or 25 years. These agreements cover systems Sunrun says it monitors, maintains and insures during the contract term.</p><p>The payment structure depends on the agreement. Sunrun’s filings say rates may be fixed for the contract term or increase at a predetermined annual percentage. Flex agreements can work differently: Sunrun’s financial disclosures distinguish between a minimum contracted payment and additional billings tied to electricity consumption.</p><p><a href={sec10k} target="_blank" rel="noreferrer">Sunrun 2025 Form 10-K at the SEC ↗</a><br/><a href={q2TenQ} target="_blank" rel="noreferrer">Sunrun Q2 2026 Form 10-Q at the SEC ↗</a></p></section>

      <section id="guarantee" className="info-section"><h2>Does a Sunrun lease or PPA guarantee solar production?</h2><p>Sunrun’s public filings say customers under Customer Agreements are covered by production guarantees, but the amount and mechanics depend on the agreement. The 2026 fleet review is more specific: newer agreements reviewed by the third party had guarantee percentages of 90%, 85% or 0%. It says most agreements it reviewed compared guaranteed production with actual production and calculated a refund, when applicable, every two years.</p><p>The same review says agreements involving battery storage do not guarantee that backup capacity will be available without interruption during every outage. Homeowners comparing solar-plus-storage offers should read the solar production language and battery-backup language separately.</p><p><a href={secFleetReview} target="_blank" rel="noreferrer">SEC-filed 2026 review of Sunrun agreements ↗</a></p></section>

      <section id="transfer" className="info-section"><h2>What happens to a Sunrun contract when you sell your house?</h2><p>Sunrun’s Form 10-K says a customer selling a home may purchase the system or assign the Customer Agreement to the buyer, provided the buyer meets applicable credit requirements and accepts the agreement. The filing also says a seller may prepay some or all remaining payments to reduce or eliminate the rate paid by the buyer.</p><p>Sunrun’s updated 2026 service-transfer page describes the same basic process from the consumer side: the solar agreement or service plan moves from one homeowner to another during a sale. The exact rights, requirements and purchase options still come from the homeowner’s actual agreement.</p><p><a href={sunrunTransfer} target="_blank" rel="noreferrer">Sunrun’s 2026 service-transfer explanation ↗</a></p></section>

      <section id="end" className="info-section"><h2>What happens at the end of a Sunrun lease?</h2><p>Sunrun’s current FAQ says a lease customer reaching the end of the agreement has three options: purchase the system at its then fair-market value, renew the lease annually or have Sunrun remove the system. Sunrun says there is no automatic default among those choices.</p><p>That end-of-term choice is different from an early buyout or purchase during the initial contract term. For those questions, the individual agreement controls the timing and pricing provisions.</p><p><a href={sunrunFaq} target="_blank" rel="noreferrer">Sunrun’s current agreement FAQ ↗</a></p></section>

      <section id="investor" className="info-section"><p className="eyebrow">The other side of the contract</p><h2>Sunrun puts a financial value on the long-term customer relationship</h2><p>Sunrun’s Q2 2026 results reported <strong>$59,377 of Subscriber Value</strong> and <strong>$55,033 of Contracted Subscriber Value</strong> per subscriber addition. Contracted Subscriber Value represents Sunrun’s estimate of the present value of upfront and future contracted cash flows associated with a new subscriber, after applying its stated methodology and discount rate.</p><p>The company’s valuation model reaches beyond the initial term. For a 25-year Customer Agreement, Sunrun assumes a five-year renewal period. For a 20-year agreement, it assumes ten years. In both cases, Sunrun says its Subscriber Value calculation assumes a 30-year customer relationship, although an actual customer may renew for additional years or purchase the system.</p><p>That does not mean a homeowner has signed a 30-year initial contract. It shows why the initial 20- or 25-year agreement matters financially to Sunrun long after installation day.</p><p><a href={q2Results} target="_blank" rel="noreferrer">Sunrun Q2 2026 financial results filed with the SEC ↗</a></p></section>

      <section className="info-section case-notice"><strong>One agreement, two very different views</strong><p>For the homeowner, the contract governs years of payments, service, roof access, production, a possible home sale and eventually what happens to the equipment. For Sunrun, long-term customer agreements also produce contracted cash flows that can be measured, financed and valued. Both descriptions come from the same underlying relationship.</p></section>

      <section id="questions" className="info-section"><h2>What to find in a Sunrun 25-year lease or PPA</h2><p>Start with the actual agreement, not the proposal headline. Find the initial term; starting monthly or per-kWh price; annual escalator or Flex billing formula; production-guarantee percentage; how production shortfalls are calculated; equipment ownership; maintenance and service terms; roof removal and reinstallation terms; home-sale transfer requirements; purchase or early-termination provisions; renewal language; and end-of-term options.</p><p>Sunrun says customers can retrieve their agreement through the Sunrun app or their online account under Contracts &amp; Docs. Keep the final agreement with the proposal and any written sales representations so the terms can be compared later.</p><p><Link href="/companies/sunrun">Sunrun Consumer Resource Center →</Link><br/><Link href="/companies/sunrun/ethics-compliance">Sunrun ethics and compliance resources →</Link><br/><Link href="/states">Find state-specific solar consumer resources →</Link></p></section>

      <section id="sources" className="info-section"><h2>Primary sources</h2><p><strong>U.S. Securities and Exchange Commission.</strong> <a href={sec10k} target="_blank" rel="noreferrer">Sunrun Inc. 2025 Form 10-K ↗</a> — agreement terms, escalators, transfers, recurring payments and contracted revenue.</p><p><strong>U.S. Securities and Exchange Commission.</strong> <a href={q2TenQ} target="_blank" rel="noreferrer">Sunrun Q2 2026 Form 10-Q ↗</a> — current customer-agreement and contracted-value disclosures.</p><p><strong>SEC-filed third-party review.</strong> <a href={secFleetReview} target="_blank" rel="noreferrer">April 2026 Sunrun fleet and agreement review ↗</a> — SHIFT, Flex and Storage Add-on terms and performance-guarantee findings.</p><p><strong>Sunrun / SEC.</strong> <a href={q2Results} target="_blank" rel="noreferrer">Second Quarter 2026 Financial Results ↗</a> — Subscriber Value, Contracted Subscriber Value and the 30-year customer-relationship assumption.</p><p><strong>Sunrun.</strong> <a href={sunrunFaq} target="_blank" rel="noreferrer">Solar FAQ ↗</a> and <a href={sunrunTransfer} target="_blank" rel="noreferrer">2026 Service Transfer guide ↗</a> — current company descriptions of agreement access, end-of-term choices and home-sale transfers.</p><p><strong>Federal Trade Commission.</strong> <a href={ftcSolar} target="_blank" rel="noreferrer">Solar Power for Your Home ↗</a> — federal consumer guidance for comparing solar leases and PPAs.</p></section>

      <section className="info-section"><h2>Continue researching Sunrun</h2><p><Link href="/companies/sunrun">Sunrun complaints, investigations and consumer resources →</Link><br/><Link href="/research/sunrun-home-depot-sales-home-visit">Sunrun at Home Depot: shopper says store pitch followed him home →</Link><br/><Link href="/research/solar-sales-financing-after-complaint">Solar sales, financing and what happens after a complaint →</Link><br/><Link href="/research">More Solar Consumer Research →</Link><br/><Link href="/methodology">Research methodology and sourcing standards →</Link></p></section>
    </InfoPage>
  </>;
}
