import type { Guide, Resource, ResourceTopic, Update } from "./types";

export const states = [
  { code: "MA", name: "Massachusetts", available: true },
  { code: "CT", name: "Connecticut", available: false },
  { code: "RI", name: "Rhode Island", available: false },
  { code: "NY", name: "New York", available: false },
  { code: "NJ", name: "New Jersey", available: false },
  { code: "PA", name: "Pennsylvania", available: false },
  { code: "CA", name: "California", available: false },
  { code: "TX", name: "Texas", available: false },
  { code: "FL", name: "Florida", available: false },
];

export const topics: { value: "all" | ResourceTopic; label: string }[] = [
  { value: "all", label: "All resources" },
  { value: "complaints", label: "Complaints" },
  { value: "utility", label: "Utility" },
  { value: "financing", label: "Financing" },
  { value: "records", label: "Records" },
  { value: "programs", label: "Programs" },
];

export const resources: Resource[] = [
  {
    id: "ma-ago-consumer-complaint",
    stateCode: "MA",
    title: "File a Massachusetts consumer complaint",
    summary: "The Attorney General's Consumer Advocacy and Response Division accepts complaints involving businesses, home improvement contracts, financing, and utility disputes.",
    publisher: "Massachusetts Attorney General's Office",
    publisherType: "government",
    topic: "complaints",
    url: "https://www.mass.gov/how-to/file-a-consumer-complaint",
    lastVerified: "Aug 16, 2026",
  },
  {
    id: "ma-dpu-utility-complaint",
    stateCode: "MA",
    title: "File a utility complaint with the DPU",
    summary: "Instructions for Massachusetts residents with unresolved concerns involving a regulated electric, gas, or water company.",
    publisher: "Massachusetts Department of Public Utilities",
    publisherType: "regulator",
    topic: "utility",
    url: "https://www.mass.gov/how-to/file-a-complaint-involving-a-gas-electric-or-water-company",
    lastVerified: "Aug 16, 2026",
  },
  {
    id: "ma-dpu-records",
    stateCode: "MA",
    title: "Request public records from the DPU",
    summary: "Official instructions for locating DPU filings and requesting records that are not already available online.",
    publisher: "Massachusetts Department of Public Utilities",
    publisherType: "regulator",
    topic: "records",
    url: "https://www.mass.gov/how-to/request-a-public-record-from-the-dpu",
    lastVerified: "Aug 16, 2026",
  },
  {
    id: "ma-electric-company",
    stateCode: "MA",
    title: "Find your electric company",
    summary: "Search the state's official city-by-city list to identify the electric company serving an address.",
    publisher: "Massachusetts Department of Public Utilities",
    publisherType: "regulator",
    topic: "utility",
    url: "https://www.mass.gov/info-details/find-my-electric-gas-and-water-company",
    lastVerified: "Aug 16, 2026",
  },
  {
    id: "ma-solar-consumer-protection",
    stateCode: "MA",
    title: "Massachusetts solar consumer protection information",
    summary: "State information about solar marketing claims, consumer precautions, complaint channels, and current program notices.",
    publisher: "Massachusetts Department of Energy Resources",
    publisherType: "government",
    topic: "programs",
    url: "https://www.mass.gov/info-details/consumer-protection",
    lastVerified: "Aug 16, 2026",
  },
  {
    id: "federal-cfpb-complaint",
    stateCode: null,
    title: "Submit a consumer finance complaint",
    summary: "The CFPB accepts complaints about consumer financial products and services and sends eligible complaints to the company for a response.",
    publisher: "Consumer Financial Protection Bureau",
    publisherType: "government",
    topic: "financing",
    url: "https://www.consumerfinance.gov/complaint/",
    lastVerified: "Aug 16, 2026",
  },
  {
    id: "federal-ftc-report-fraud",
    stateCode: null,
    title: "Report fraud to the FTC",
    summary: "The Federal Trade Commission's official reporting channel for scams, deceptive practices, and other consumer fraud.",
    publisher: "Federal Trade Commission",
    publisherType: "government",
    topic: "complaints",
    url: "https://reportfraud.ftc.gov/",
    lastVerified: "Aug 16, 2026",
  },
  {
    id: "bbb-complaint",
    stateCode: null,
    title: "File a BBB complaint",
    summary: "BBB's complaint channel may send a complaint to a business for a response. BBB is a private nonprofit, not a government agency or regulator.",
    publisher: "Better Business Bureau",
    publisherType: "private_nonprofit",
    topic: "complaints",
    url: "https://www.bbb.org/file-a-complaint",
    lastVerified: "Aug 16, 2026",
  },
];

export const guides: Guide[] = [
  {
    id: "organize-record",
    stateCode: null,
    title: "Build a clean project record",
    summary: "Create a dated, source-backed file before contacting an agency or asking a research question.",
    timeLabel: "15-30 minutes",
    steps: [
      { title: "Create a timeline", detail: "List the major events in date order using short, factual descriptions." },
      { title: "Gather primary documents", detail: "Keep contracts, change orders, designs, permits, inspection records, bills, and written correspondence together." },
      { title: "Keep originals intact", detail: "Submit copies when requested and retain original files and unedited messages." },
      { title: "Write down the unresolved question", detail: "Separate what the documents show from what is still missing or unclear." },
    ],
    sourceTitle: "Resolving a consumer complaint",
    sourceUrl: "https://www.mass.gov/info-details/resolving-a-consumer-complaint",
    lastVerified: "Aug 16, 2026",
  },
  {
    id: "ma-ago-complaint-guide",
    stateCode: "MA",
    title: "Prepare a Massachusetts AGO complaint",
    summary: "A plain-language checklist based on the Attorney General's published filing instructions.",
    timeLabel: "20-40 minutes",
    steps: [
      { title: "Confirm the channel", detail: "Review the AGO page to make sure the complaint type is accepted." },
      { title: "Summarize the issue", detail: "Use dates, names, amounts, and a short description of what remains unresolved." },
      { title: "Follow the document instructions", detail: "The AGO says not to send additional documentation until requested." },
      { title: "Save your submission", detail: "Use the option to save or print a copy after filing." },
    ],
    sourceTitle: "File a consumer complaint",
    sourceUrl: "https://www.mass.gov/how-to/file-a-consumer-complaint",
    lastVerified: "Aug 16, 2026",
  },
  {
    id: "ma-30-day-information",
    stateCode: "MA",
    title: "Review the official 30-day demand letter information",
    summary: "An index of the information the Massachusetts Courts page says a letter should contain. This is public information, not individualized guidance.",
    timeLabel: "Official checklist",
    steps: [
      { title: "Read the state page first", detail: "The official page explains when this process is used and lists exceptions." },
      { title: "Review the required information", detail: "The state lists identity, the conduct at issue, dates and facts, the claimed injury, and the requested relief." },
      { title: "Use the state sample only as a reference", detail: "Do not rely on a third-party template or assume a sample fits a particular situation." },
      { title: "Track delivery and response dates", detail: "The state recommends keeping a copy and describes certified and regular mail options." },
    ],
    sourceTitle: "30 Day Demand Letter",
    sourceUrl: "https://www.mass.gov/info-details/30-day-demand-letter",
    lastVerified: "Aug 16, 2026",
  },
  {
    id: "bbb-complaint-guide",
    stateCode: null,
    title: "Prepare a BBB complaint",
    summary: "A simple checklist for using BBB's own complaint channel. BBB is a private nonprofit, not a regulator.",
    timeLabel: "10-20 minutes",
    steps: [
      { title: "Confirm the business", detail: "Use the business name and location requested by the BBB form." },
      { title: "Keep the account factual", detail: "Use a short timeline and describe the unresolved issue without speculation." },
      { title: "State the requested resolution", detail: "Describe the response or correction you are asking the business to consider." },
      { title: "Save the case information", detail: "Keep the confirmation and any business response with the rest of your project record." },
    ],
    sourceTitle: "BBB complaint portal",
    sourceUrl: "https://www.bbb.org/file-a-complaint",
    lastVerified: "Aug 16, 2026",
  },
];

export const updates: Update[] = [
  {
    id: "ma-solar-for-all-status",
    stateCode: "MA",
    title: "Massachusetts Solar for All remains paused",
    summary: "The state's consumer protection page says program funding is paused and warns residents about organizations claiming to represent the program.",
    publisher: "Mass.gov",
    publishedAt: "Verified Aug 16, 2026",
    url: "https://www.mass.gov/info-details/consumer-protection",
  },
  {
    id: "ma-consumer-law-update",
    stateCode: "MA",
    title: "Massachusetts refreshed its consumer protection law index",
    summary: "The state's law library page collects current statutes, regulations, forms, court materials, and official complaint channels.",
    publisher: "Massachusetts Trial Court Law Libraries",
    publishedAt: "Updated Jul 2026",
    url: "https://www.mass.gov/info-details/massachusetts-law-about-consumer-protection",
  },
];

