import type { Metadata } from "next";
import Link from "next/link";
const canonicalUrl="https://solarcomplaint.com/goodleap"; const reviewedDate="2026-09-16";
export const metadata:Metadata={title:"GoodLeap Solar Financing: Lawsuits & Consumer Research",description:"GoodLeap solar financing research based on court records, Attorney General actions, arbitration rulings, and official consumer resources.",alternates:{canonical:"/goodleap"},openGraph:{title:"GoodLeap Solar Financing: What the Public Record Shows",description:"Independent research on GoodLeap solar financing using court records, government filings, and primary sources.",url:"/goodleap",type:"website"}};
const states=[{abbr:"MN",state:"Minnesota",detail:"The Attorney General sued GoodLeap and three other solar lenders over alleged hidden dealer fees in financed solar transactions.",href:"/goodleap/states/minnesota",stateHref:"/states/minnesota"},{abbr:"VA",state:"Virginia",detail:"A 2026 Attorney General case names GoodLeap among lenders connected to the Power Home Solar / Pink Energy record.",href:"/goodleap/states/virginia",stateHref:"/states/virginia"}] as const;
export default function Page(){const sd={"@context":"https://schema.org","@type":"CollectionPage","@id":`${canonicalUrl}#page`,name:"GoodLeap Solar Financing: What the Public Record Shows",url:canonicalUrl,dateModified:reviewedDate,isPartOf:{"@id":"https://solarcomplaint.com/#website"},publisher:{"@id":"https://solarcomplaint.com/#publisher"},about:{"@type":"Organization",name:"GoodLeap, LLC",alternateName:"Loanpal"}};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(sd)}}/><main className="gl-main"><div className="gl-page"><p className="gl-eyebrow">GoodLeap research</p><h1>GoodLeap solar financing: what the public record shows</h1><p className="gl-deck">GoodLeap, formerly Loanpal, appears in solar-financing lawsuits, Attorney General cases, and arbitration disputes around the country. This hub organizes the strongest records by state and separates allegations from court rulings.</p><div className="gl-review-line"><time dateTime={reviewedDate}>Reviewed September 16, 2026</time><span>·</span><Link href="/methodology">Methodology</Link><span>·</span><Link href="/corrections">Corrections</Link></div><div className="gl-actions"><Link className="gl-button gl-button-primary" href="/#questions">Get free research assistance</Link><Link className="gl-button" href="/goodleap/states">Browse by state</Link></div><div className="gl-summary"><p>Start with the state record. We connect GoodLeap-specific research to SolarComplaint.com state hubs so homeowners can move from a lender record to regulators, complaint channels, court material, and related solar research without starting over.</p></div>
<section className="gl-section"><h2>Published state research</h2><div className="gl-published-list">{states.map(s=><article className="gl-published-item" key={s.abbr}><span className="gl-state-abbr">{s.abbr}</span><div><h3>{s.state}</h3><p>{s.detail}</p><Link href={s.href}>Read GoodLeap research →</Link><br/><Link href={s.stateHref}>Open all {s.state} solar resources →</Link></div></article>)}</div></section>
<section className="gl-section"><h2>Newer records under review</h2><p><strong>Maryland:</strong> the 2026 <em>Arias v. GoodLeap</em> record includes a federal ruling addressing contract formation and arbitration. That procedural ruling is kept separate from the merits of the consumer claims. <Link className="gl-text-link" href="/states/maryland">Maryland solar resources →</Link></p><p><strong>Texas:</strong> 2026 court records include GoodLeap arbitration and contract-formation disputes. <Link className="gl-text-link" href="/states/texas">Texas solar resources →</Link></p><p><strong>Florida:</strong> GoodLeap also appears as a plaintiff in 2026 litigation involving solar-cancellation businesses. That record is tracked separately from homeowner claims against GoodLeap. <Link className="gl-text-link" href="/states/florida">Florida solar resources →</Link></p></section>
<section className="gl-section"><h2>Related SolarComplaint.com research</h2><p><Link className="gl-text-link" href="/cases/titan-solar-power">Titan Solar Power closure and bankruptcy research →</Link><br/><Link className="gl-text-link" href="/research">All solar consumer research →</Link><br/><Link className="gl-text-link" href="/resources">Consumer resources →</Link></p></section>
<section className="gl-section"><h2>FLAG tracker</h2><p><strong>FLAG</strong> means <strong>Financing Litigation &amp; Arbitration involving GoodLeap</strong>. It is an editorial research label, not a finding of wrongdoing. <Link className="gl-text-link" href="/goodleap/states">Open the state tracker →</Link></p></section>
<section className="gl-help-box"><h2>Have a GoodLeap solar financing issue?</h2><p>Send your state, city or town, and a short description. We will look for public records, regulators, complaint channels, and source-backed information.</p><div className="gl-actions"><Link className="gl-button gl-button-primary" href="/#questions">Request free research assistance</Link><Link className="gl-button" href="/goodleap/resources">Official consumer resources</Link></div></section></div></main></>}
